[project]
name = "bi-trabajo-final"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "faker>=33.3.0",
    "orjson>=3.10.13",
    "psycopg2-binary>=2.9.10",
    "sqlalchemy>=2.0.36",
]
